"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase-browser";

type Opportunity={id:string;opportunity_type:string;title:string;reason:string;estimated_value:number|null;confidence:number|null;status:string;created_at:string};

export default function ArkOpportunities(){
 const [items,setItems]=useState<Opportunity[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{if(!supabase){setLoading(false);return;} const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false);return;} const {data:m}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).limit(1); const org=m?.[0]?.organization_id; if(!org){setLoading(false);return;} const {data}=await supabase.from("ark_opportunities").select("id,opportunity_type,title,reason,estimated_value,confidence,status,created_at").eq("organization_id",org).order("created_at",{ascending:false}); setItems(data??[]); setLoading(false);})();},[]);
 const total=items.reduce((s,i)=>s+(i.estimated_value??0),0); return <main className="ark-shell"><header className="ark-topbar"><div className="ark-brand"><Link href="/ark">ORBARK</Link><span>/</span><strong>Opportunities</strong></div><nav className="ark-nav"><Link href="/ark">Brief</Link><Link className="active" href="/ark/opportunities">Opportunities</Link><Link href="/ark/memory">Memory</Link></nav></header><div className="ark-page"><section className="ark-hero"><div><p className="eyebrow">ARK RADAR</p><h1>Where the business<br/>can improve.</h1><p>Every opportunity here must come from real business signals. ARK never invents revenue.</p></div><div className="ark-state"><span/>{loading?"Scanning signals":"Radar active"}</div></section><section className="brief-grid"><article className="brief-card focus-card"><p className="eyebrow">REVENUE OPPORTUNITIES</p><h2>{items.length?`$${total.toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:0})}`:"No verified value yet"}</h2><p className="muted">{items.length?`${items.length} open signals with a recorded value.`:"Connect tools and capture events before ARK estimates anything."}</p></article><article className="brief-card metric-focus"><p className="eyebrow">OPEN</p><strong>{items.filter(i=>i.status==='open'||i.status==='recommended').length}</strong><span>opportunities</span></article><article className="brief-card metric-focus"><p className="eyebrow">HIGH CONFIDENCE</p><strong>{items.filter(i=>(i.confidence??0)>=.8).length}</strong><span>signals at 80%+</span></article></section><section className="brief-section"><div className="section-head"><div><p className="eyebrow">ARK FINDINGS</p><h2>Verified business opportunities</h2></div></div><div className="memory-list">{items.length?items.map(i=><article className="op-row" key={i.id}><div className="op-main"><span className="memory-cat">{i.opportunity_type}</span><h3>{i.title}</h3><p>{i.reason}</p><small>{i.estimated_value==null?"Value not estimated":`Estimated value: $${i.estimated_value.toLocaleString()}`} · {i.confidence==null?"Confidence —":`Confidence ${Math.round(i.confidence*100)}%`}</small></div><span className={`run-status ${i.status}`}>{i.status}</span></article>):<div className="empty-state"><strong>ARK has not verified an opportunity yet.</strong><span>This stays empty until connected business data produces a defensible signal.</span></div>}</div></section></div><style jsx>{`.op-row{display:flex;justify-content:space-between;gap:20px;padding:18px;border-bottom:1px solid rgba(0,0,0,.05)}.op-row:last-child{border-bottom:0}.op-main h3{margin:5px 0;font-size:12px}.op-main p{margin:5px 0;color:#777;font-size:10px;line-height:1.5}.op-main small{color:#aaa;font-size:8px}`}</style></main>;
}
