"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase-browser";

const categories=["messages","emails","payments","refunds","calendar","crm","marketing","data","financial_actions"];
const levels=["observe","recommend","approve","auto"] as const;

export default function ArkPermissions(){
 const [orgId,setOrgId]=useState<string|null>(null); const [values,setValues]=useState<Record<string,string>>({}); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{(async()=>{if(!supabase)return; const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const {data:m}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).limit(1); const org=m?.[0]?.organization_id; if(!org)return; setOrgId(org); const {data:p}=await supabase.from("ark_permissions").select("category,autonomy_level").eq("organization_id",org); const map:Record<string,string>={}; categories.forEach(c=>map[c]=p?.find(x=>x.category===c)?.autonomy_level??"observe"); setValues(map);})();},[]);
 async function save(){if(!supabase||!orgId)return;setSaving(true);setMessage(""); const rows=categories.map(category=>({organization_id:orgId,category,autonomy_level:values[category]??"observe"})); const {error}=await supabase.from("ark_permissions").upsert(rows,{onConflict:"organization_id,category"}); setMessage(error?error.message:"Permissions saved.");setSaving(false);}
 return <main className="ark-shell"><header className="ark-topbar"><div className="ark-brand"><Link href="/ark">ORBARK</Link><span>/</span><strong>Permissions</strong></div><nav className="ark-nav"><Link href="/ark">Brief</Link><Link href="/ark/opportunities">Opportunities</Link><Link href="/ark/recommendations">Recommendations</Link><Link className="active" href="/ark/permissions">Permissions</Link></nav></header><div className="ark-page"><section className="ark-hero"><div><p className="eyebrow">HUMAN CONTROL</p><h1>Give ARK<br/>room to act.</h1><p>Start conservative. Increase autonomy only where the business is comfortable with automatic action.</p></div><div className="ark-state"><span/>Permissions enforced</div></section>{message&&<div className="notice">{message}</div>}<section className="brief-section"><div className="section-head"><div><p className="eyebrow">AUTONOMY LEVELS</p><h2>What ARK is allowed to do</h2></div><button className="brief-button" disabled={saving} onClick={save}>{saving?"Saving…":"Save permissions"}</button></div><div className="memory-list">{categories.map(category=><div className="perm-row" key={category}><div><strong>{category.replace("_"," ")}</strong><small>ARK actions in this category</small></div><select value={values[category]??"observe"} onChange={e=>setValues(v=>({...v,[category]:e.target.value}))}>{levels.map(level=><option key={level} value={level}>{level}</option>)}</select></div>)}</div></section></div><style jsx>{`.notice{margin-bottom:18px;padding:12px 14px;border:1px solid rgba(0,0,0,.08);border-radius:12px;background:rgba(255,255,255,.8);font-size:10px;color:#555}.perm-row{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:16px 18px;border-bottom:1px solid rgba(0,0,0,.05)}.perm-row:last-child{border-bottom:0}.perm-row strong{display:block;text-transform:capitalize;font-size:11px}.perm-row small{display:block;margin-top:4px;color:#aaa;font-size:8px}.perm-row select{border:1px solid rgba(0,0,0,.1);border-radius:9px;padding:7px 9px;background:#fff;font-size:9px;text-transform:capitalize}`}</style></main>;
}
